language: python
python:
  - "3.8"
dist: bionic
install:
  - pip3 install pipenv
  - pipenv install
script:
  - pipenv lock --pre
  - pipenv install -e .
  - pipenv run py.test
branches:
  only:
  - master
