language: python

python:
  - "3.8"

dist: bionic

install:
  - pip3 install pipenv
  - pipenv install

script:
  - pipenv run pytest --cov=./

after_success:
  - codecov

branches:
  only:
  - master
